feat: complete
timoff99/Tasks pull request #1
Opened 2021-12-08 19:14 UTC by timoff99

2021-12-08 22:17 UTC, adryianSiarheyeu requested changes

2021-12-08 22:17 UTC, adryianSiarheyeu commented on 6rating.js
> +}
it could be implemented through the single reduce method to avoid looping twice

2021-12-08 22:17 UTC, adryianSiarheyeu commented on 7square.js
> +  const arrOfSquareArr = arr.reduce((prev, cur, index) => {
strange name arr of ... arr

2021-12-09 12:08 UTC, timoff99 commented on 1cutString.js
> +  return `${newWorld}...`
I didn't understand what the problem is

2021-12-09 12:09 UTC, timoff99 commented on 2maxFrequent.js
> +  }, {})
I don't know how to do without `Map`

2021-12-10 12:56 UTC, merged